[package]
name = "cargo-audit-action-repro"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.9.1"

# synthetic change
